// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionDirectives.DbContexts;

#nullable disable

namespace ProductionDirectives.Migrations
{
    [DbContext(typeof(ProductionDirectivesDbContext))]
    partial class ProductionDirectivesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalStage")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChiThiMaus");

                    b.HasDiscriminator().HasValue("ChiThiMau");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_ChiThiMau")
                        .HasColumnType("uuid");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RuleStandard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_ChiThiMau");

                    b.ToTable("ChiThiMau_ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_ChiThiPheDuyet")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleStandard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChiThiPheDuyet_ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThi_Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RuleStandard")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChiThi_Templates");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet", b =>
                {
                    b.HasBaseType("ProductionDirectives.Models.ChiThiMau");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PICCreate")
                        .HasColumnType("uuid");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDandory_Done")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("ChiThiPheDuyet");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau_ChiTiet", b =>
                {
                    b.HasOne("ProductionDirectives.Models.ChiThiMau", "ChiThiMau")
                        .WithMany("ChiTiets")
                        .HasForeignKey("Id_ChiThiMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiThiMau");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau", b =>
                {
                    b.Navigation("ChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
