// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionDirectives.DbContexts;

#nullable disable

namespace ProductionDirectives.Migrations
{
    [DbContext(typeof(ProductionDirectivesDbContext))]
    partial class ProductionDirectivesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalStage")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChiThiMaus");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_ChiThiMau")
                        .HasColumnType("uuid");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RuleStandard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_ChiThiMau");

                    b.ToTable("ChiThiMau_ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PICCreate")
                        .HasColumnType("uuid");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalStage")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStep")
                        .HasColumnType("integer");

                    b.Property<bool>("isDandory_Done")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PICCreate");

                    b.ToTable("ChiThiPheDuyets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_ChiThiPheDuyet")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PICCheckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleStandard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_ChiThiPheDuyet");

                    b.HasIndex("PICCheckId");

                    b.ToTable("ChiThiPheDuyet_ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThi_Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<int>("NumberOrder")
                        .HasColumnType("integer");

                    b.Property<string>("RuleStandard")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChiThi_Templates");
                });

            modelBuilder.Entity("ProductionDirectives.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau_ChiTiet", b =>
                {
                    b.HasOne("ProductionDirectives.Models.ChiThiMau", "ChiThiMau")
                        .WithMany("ChiTiets")
                        .HasForeignKey("Id_ChiThiMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiThiMau");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet", b =>
                {
                    b.HasOne("ProductionDirectives.Models.NguoiDung", "PICCreateNguoiDung")
                        .WithMany("ChiThiPheDuyets")
                        .HasForeignKey("PICCreate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PICCreateNguoiDung");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet_ChiTiet", b =>
                {
                    b.HasOne("ProductionDirectives.Models.ChiThiPheDuyet", "ChiThiPheDuyet")
                        .WithMany("ChiThiPheDuyet_ChiTiets")
                        .HasForeignKey("Id_ChiThiPheDuyet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionDirectives.Models.NguoiDung", "PICCheck")
                        .WithMany("ChiThiPheDuyetChiTiets")
                        .HasForeignKey("PICCheckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChiThiPheDuyet");

                    b.Navigation("PICCheck");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiMau", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.ChiThiPheDuyet", b =>
                {
                    b.Navigation("ChiThiPheDuyet_ChiTiets");
                });

            modelBuilder.Entity("ProductionDirectives.Models.NguoiDung", b =>
                {
                    b.Navigation("ChiThiPheDuyetChiTiets");

                    b.Navigation("ChiThiPheDuyets");
                });
#pragma warning restore 612, 618
        }
    }
}
